name: Build kube-universe image
on:
  workflow_dispatch:
  push:

permissions:
  contents: write
  packages: write

jobs:
  build_agent:
    name: Build ecs_daemon image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: Checkout files

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          push: true
          platforms: linux/arm64,linux/amd64
          tags: ghcr.io/pmh-only/kube-universe:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
